# coding: utf-8

# flake8: noqa

"""
    Swagger Petstore

    This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.7
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "PetApi",
    "StoreApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiResponse",
    "Category",
    "Order",
    "Pet",
    "Tag",
    "User",
]

# import apis into sdk package
from petstore_api.api.pet_api import PetApi as PetApi
from petstore_api.api.store_api import StoreApi as StoreApi
from petstore_api.api.user_api import UserApi as UserApi

# import ApiClient
from petstore_api.api_response import ApiResponse as ApiResponse
from petstore_api.api_client import ApiClient as ApiClient
from petstore_api.configuration import Configuration as Configuration
from petstore_api.exceptions import OpenApiException as OpenApiException
from petstore_api.exceptions import ApiTypeError as ApiTypeError
from petstore_api.exceptions import ApiValueError as ApiValueError
from petstore_api.exceptions import ApiKeyError as ApiKeyError
from petstore_api.exceptions import ApiAttributeError as ApiAttributeError
from petstore_api.exceptions import ApiException as ApiException

# import models into sdk package
from petstore_api.models.api_response import ApiResponse as ApiResponse
from petstore_api.models.category import Category as Category
from petstore_api.models.order import Order as Order
from petstore_api.models.pet import Pet as Pet
from petstore_api.models.tag import Tag as Tag
from petstore_api.models.user import User as User

