# coding: utf-8

# flake8: noqa
"""
    Swagger Petstore

    This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.7
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from petstore_api.models.api_response import ApiResponse
from petstore_api.models.category import Category
from petstore_api.models.order import Order
from petstore_api.models.pet import Pet
from petstore_api.models.tag import Tag
from petstore_api.models.user import User

